services:
  go:
    build:
      context: .
      dockerfile: Dockerfile.buildkite
    volumes:
      - .:/work
    working_dir: /work
    environment:
      - BUILDKITE_TAG
      - GITHUB_TOKEN

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'cultureamp/ecr-scan-results']
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester:v4.1.1
    volumes:
      - ".:/plugin"
