name: ECR Scan Results
description: >
  Retrieves vulnerability scan results from ECR, creating a report as an
  annotation on the build. Will fail the step if vulnerabilities exist (though
  this is configurable).
author: https://github.com/buildkite
requirements:
  - docker
  - jq
configuration:
  properties:
    image-name:
      type: string
    max-criticals:
      type: string
    max-highs:
      type: string
    image-label:
      type: string
    ignore:
      type: array
    ignore-file:
      type: string
    help:
      type: string

  additionalProperties: false
