steps:
  - label: ":broom: Lint"
    key: lint
    command: "make lint"
    plugins:
      docker-compose#v4.8.0:
        run: go

  - label: ":test-analytics: Test"
    key: test
    command: "make test"
    plugins:
      docker-compose#v4.8.0:
        run: go

  - label: ":golang: Build"
    key: build
    command: "make ecrscanresults"
    plugins:
      docker-compose#v4.8.0:
        run: go
